apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/t8c-certified.turbonomic: ""
    {{- include "ocp-turbonomic.labels" . | nindent 4 }}    
  name: t8c-certified
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: t8c-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
